ALTER TABLE sales_invoices
  ADD COLUMN IF NOT EXISTS shipping_cost DECIMAL(10,2) NOT NULL DEFAULT 0;

ALTER TABLE products
  ADD COLUMN IF NOT EXISTS sku VARCHAR(50);

CREATE UNIQUE INDEX IF NOT EXISTS products_sku_key ON products(sku) WHERE sku IS NOT NULL;
