CREATE TABLE IF NOT EXISTS printers (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  model VARCHAR(100),
  active BOOLEAN NOT NULL DEFAULT true,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO printers (name, model, sort_order) VALUES
  ('Printer 1', NULL, 0),
  ('Printer 2', NULL, 1)
ON CONFLICT DO NOTHING;
